#!/bin/bash


DS=$(bash rando 1 5)
DX=$(bash rando 7 2000)
DY=$(bash rando 7 2000)
# DZ=$(bash rando 1 3)
DZ=0
#DRX=$(bash rando 1 800)
DRX=0
#DRY=$(bash rando 1 700)
DRY=0
DRZ=$(bash randon 10 200)
IMAGE=$1

cat slide |sed "s/{{DS}}/$DS/g"|sed "s/{{DX}}/$DX/g"|sed "s/{{DY}}/$DY/g"|sed "s/{{DZ}}/$DZ/g"|sed "s/{{DRX}}/$DRX/g"|sed "s/{{DRY}}/$DRY/g"|sed "s/{{DRZ}}/$DRZ/g"|sed "s!{{image}}!$IMAGE!g"
